### ISSUE TITLE
add build plan  info to matrix 

### ISSUE THREAD

**Issue by cartazio** [haskell-CI/hackage-matrix-builder#54] opened 2019-03-15 00:31 UTC
would be great to know what versions of deps were picked by different combinations that build /fail

**Comment by cartazio** [comment] 2019-03-15 00:36
```
8:34 PM <hvr> curl -s https://matrix.hackage.haskell.org/api/v2/units/$JID/deps  | jq -C . | less -R
8:34 PM <hvr> curl -s https://matrix.hackage.haskell.org/api/v2/units/$JID  | jq -C . | less -R
8:34 PM <hvr> the JID is the UUID you see in the /ng UI
8:34 PM <hvr> for a given cell
8:35 PM <hvr> in future that information is supposed to be provided pretty printed in the UI proper
8:35 PM <hvr> but for now, you have to make due with the webservice

```

**Comment by hvr** [comment] 2019-03-15 00:38
Duplicate of #52

**Comment by cartazio** [comment] 2019-03-15 00:39
so an example would https://matrix.hackage.haskell.org/api/v2/units/3f37c48a-df20-c7e6-8fbf-07d4d861e24d/deps

**Closed as completed** 2019-03-15 00:38 UTC
