### ISSUE TITLE
Include package candiates into the matrix

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-CI/hackage-matrix-builder#71] opened 2020-02-10 00:18 UTC
I think it'd be very useful to have the Matrix reporting the status of candidates along with the releases. This would relieve a developer from manual testing for compatibility with older versions of GHC. What do you think?

**Comment by hvr** [comment] 2020-05-11 14:31
Thanks; but this is effectively a duplicate of #19 

The reason it's not implemented yet is that this requires refactoring (and fixing some tech-debt) and extending the database schema in order to support candidates.

**Comment by hvr** [comment] 2020-05-11 14:31
Duplicate of #19

**Closed as completed by hvr** 2020-05-11 14:31 UTC

**Comment by ulysses4ever** [comment] 2020-05-11 23:09
I see, thanks!
